config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'users'
  resources :form_barats 
  
  root :to => "pages#index"

  get 'wilayah_tengah' => 'wilayah_tengahs#index'
  get 'wilayah_tengah/gorontalo' => 'wilayah_tengahs#gorontalo'
  get 'wilayah_tengah/kalimantanbarat' => 'wilayah_tengahs#kalimantan_barat'
  get 'wilayah_tengah/kalimantanselatan' => 'wilayah_tengahs#kalimantan_selatan'
  get 'wilayah_tengah/kalimantantimur' => 'wilayah_tengahs#kalimantan_timur'
  get 'wilayah_tengah/kalimantanutara' => 'wilayah_tengahs#kalimantan_utara'
  get 'wilayah_tengah/nusatenggaratimur' => 'wilayah_tengahs#nusa_tenggara_timur'
  get 'wilayah_tengah/nusatenggarabarat' => 'wilayah_tengahs#nusa_tenggara_barat'
  get 'wilayah_tengah/sulawesitengah' => 'wilayah_tengahs#sulawesi_tengah'
  get 'wilayah_tengah/sulawesitenggara' => 'wilayah_tengahs#sulawesi_tenggara'

  get 'wilayah_tengah/mydata' => 'survey_forms#tengah_mydata'


  resources :survey_forms

  resources :users do
    resources :survey_forms
  end
end

app/controllers/wilayah_tengahs_controller.rb
class WilayahTengahsController < ApplicationController
  before_action :set_wilayah_tengah, only: [:show, :edit, :update, :destroy]

  # GET /wilayah_tengahs
  # GET /wilayah_tengahs.json
  def index
    @survey_forms = SurveyForm.all
  end

  def gorontalo
    @survey_forms = SurveyForm.all.where(provinsi:"Gorontalo")
  end

  def kalimantan_barat
    #@survey_forms = SurveyForm.all
     @survey_forms = SurveyForm.all.where(provinsi:"Kalimantan Barat")
  end

  def kalimantan_selatan
    @survey_forms = SurveyForm.all.where(provinsi:"Kalimantan Selatan")
  end

  def kalimantan_timur
    @survey_forms = SurveyForm.all.where(provinsi:"Kalimantan Timur")
  end

  def kalimantan_utara
    @survey_forms = SurveyForm.all.where(provinsi:"Kalimantan Utara")
  end

  def nusa_tenggara_timur
    @survey_forms = SurveyForm.all.where(provinsi:"Nusa Tenggara Timur")
  end

  def nusa_tenggara_barat
    @survey_forms = SurveyForm.all.where(provinsi:"Nusa Tenggara Barat")
  end

  def sulawesi_tengah
    @survey_forms = SurveyForm.all.where(provinsi:"Sulawesi Tengah")
  end

  def sulawesi_tenggara
    @survey_forms = SurveyForm.all.where(provinsi:"Sulawesi Tenggara")
  end
end

app/helpers/wilayah_tengahs_helper.rb
module WilayahTengahsHelper
end

app/views/wilayah_tengahs/gorontalo.html.erb
 <div class="container-fluid">
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Tengah Provinsi Gorontalo</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-1">
                <%= pie_chart SurveyForm.where(provinsi:"Gorontalo").group(:kabupaten).count, discrete: true, donut:true, height: "400px", messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>
  </div>     

  <div class="container">
    <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Nama Lokasi</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
            <th style="text-align: center;">Tanggal Dibuat</th>
          </tr>
        </thead>

        <tbody>
          <% @survey_forms.each do |survey_form| %>
            <tr>
              <td data-title="Provinsi"><%= survey_form.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= survey_form.kabupaten %></td>
              <td data-title="Kecamatan"><%= survey_form.kecamatan %></td>
              <td data-title="Kelurahan"><%= survey_form.kelurahan %></td>
              <td data-title="Nama Lokasi"><%= survey_form.nama_lokasi %></td>
              <td data-title="Lattide"><%= survey_form.lattide %></td>
              <td data-title="Longitude"><%= survey_form.longitude %></td>
              <td data-title="Tanggal Dibuat"><%= survey_form.created_at.strftime '%Y-%m-%d' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>
</div>    
  </div>   

app/views/wilayah_tengahs/index.html.erb
<div class="container-fluid">
<center><h3>Data Survey Wilayah Tengah Yang Sudah Masuk</h3></center><hr>  
<hr>
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Tengah</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-4 col-md-4">
                <div class="table-responsive">
                  <table style="width:100%; color: #000">
                        <tr>
                          <th style="width:10%; text-align: center;">NO</th>
                          <th style="width:40%;text-align: center;">Provinsi</th>
                          <th style="width:25%;text-align: center;">Target Data Masuk</th>
                          <th style="width:25%;text-align: center;">Jumlah Data Masuk</th> 
                        </tr>
                        <tr>
                          <td style="text-align: center;">1</td>
                          <td><%= link_to "Gorontalo", wilayah_tengah_gorontalo_path %></td>
                          <td style="text-align: center;">27</td>
                          <td style="text-align: center;"><%= @survey_forms.where(provinsi:"Gorontalo").count%></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">2</td>
                          <td><%= link_to "Kalimantan Barat", wilayah_tengah_kalimantanbarat_path %></td>
                          <td style="text-align: center;">107</td>
                          <td style="text-align: center;"><%= @survey_forms.where(provinsi:"Kalimantan Barat").count%></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">3</td>
                          <td><%= link_to "Kalimantan Selatan", wilayah_tengah_kalimantanselatan_path %>
                          <td style="text-align: center;">16</td>
                          <td style="text-align: center;"><%= @survey_forms.where(provinsi:"Kalimantan Selatan").count%></td>  
                          </td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">4</td>
                          <td><%= link_to "Kalimantan Timur", wilayah_tengah_kalimantantimur_path %></td>
                           <td style="text-align: center;">13</td>
                          <td style="text-align: center;"><%= @survey_forms.where(provinsi:"Kalimantan Timur").count%></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">5</td>
                          <td><%= link_to "Kalimantan Utara", wilayah_tengah_kalimantanutara_path %></td>
                          <td style="text-align: center;">11</td>
                          <td style="text-align: center;"><%= @survey_forms.where(provinsi:"Kalimantan Utara").count%></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">6</td>
                          <td><%= link_to "Nusa Tenggara Barat", wilayah_tengah_nusatenggarabarat_path %>
                          <td style="text-align: center;">22</td>
                          <td style="text-align: center;"><%= @survey_forms.where(provinsi:"NUsa Tenggara Barat").count%></td>
                          </td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">7</td>
                          <td><%= link_to "Nusa Tenggara Timur", wilayah_tengah_nusatenggaratimur_path%>
                          <td style="text-align: center;">166</td>
                          <td style="text-align: center;"><%= @survey_forms.where(provinsi:"Nusa Tenggara Timur").count%></td>
                          </td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">8</td>
                          <td><%= link_to "Sulawesi Tengah", wilayah_tengah_sulawesitengah_path %></td>
                          <td style="text-align: center;">80</td>
                          <td style="text-align: center;"><%= @survey_forms.where(provinsi:"Sulawesi Tengah").count%></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">9</td>
                          <td><%= link_to "Sulawesi Tenggara", wilayah_tengah_sulawesitenggara_path %></td>
                          <td style="text-align: center;">37</td>
                          <td style="text-align: center;"><%= @survey_forms.where(provinsi:"Sulawesi Tenggara").count%></td>
                        </tr>
                  </table>
                </div>
                </div>
                <div class= "col-lg-7 col-md-7">
                  
                    <%= pie_chart SurveyForm.group(:provinsi).count, donut:true, messages: {empty: "No data"} %>
                  
                </div>
             </div>
            </div>
        </div>
  </div>
  
  <div class="row">
    <div class="col-lg-12 col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Tengah</strong></h5>  
            </div>
            <ul class="nav nav-tabs">
                  <li class="active"><a data-toggle="tab" href="#home">Per-Hari</a></li>
                  <li><a data-toggle="tab" href="#menu1">Per-Minggu</a></li>
                  <li><a data-toggle="tab" href="#menu2">Per-Bulan</a></li>
                  <li><a data-toggle="tab" href="#menu3">Per-Tahun</a></li>
                </ul><br>  
            <div class="panel-body">
              <div class="tab-content">
                  <div id="home" class="tab-pane fade in active">
                         <div class= "col-md-12">
                              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <%#= line_chart SurveyForm.group_by_day(:created_at, format: "%a").count %>
                               <%= line_chart @survey_forms.group_by_day(:created_at, format: "%d %B , %Y").count, discrete: true, messages: {empty: "No data"}, xtitle: "Hari", ytitle: "Jumlah Data Masuk" %>;

                              </div>
                        </div>
                  </div>
                  <div id="menu1" class="tab-pane fade">
                         <div class= "col-md-12">
                              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <%#= line_chart SurveyForm.group_by_day(:created_at, format: "%a").count %>
                               <%= line_chart @survey_forms.group_by_week(:created_at, format: "%d %B, %Y").count, discrete: true, messages: {empty: "No data"}, xtitle: "Minggu", ytitle: "Jumlah Data Masuk" %>;

                              </div>
                        </div>
                  </div>
                  <div id="menu2" class="tab-pane fade">
                        <div class= "col-md-12">
                              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <%#= line_chart SurveyForm.group_by_day(:created_at, format: "%a").count %>
                               <%= line_chart @survey_forms.group_by_month(:created_at, format: "%B %Y").count, discrete: true, messages: {empty: "No data"}, xtitle: "Bulan", ytitle: "Jumlah Data Masuk" %>;

                              </div>
                        </div>
                  </div>
                  <div id="menu3" class="tab-pane fade">
                        <div class= "col-md-12">
                              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <%#= line_chart SurveyForm.group_by_day(:created_at, format: "%a").count %>
                               <%= line_chart @survey_forms.group_by_year(:created_at, format: "%Y").count, discrete: true, messages: {empty: "No data"}, xtitle: "Tahun", ytitle: "Jumlah Data Masuk" %>;
                              </div>
                        </div>
                  </div>
               </div
            </div>
          </div>
        </div>
  </div>
        <!-- statics end -->
  <br>
  
  <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Nama Lokasi</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
            <th style="text-align: center;">Tanggal Dibuat</th>
          </tr>
        </thead>

        <tbody>
          <% @survey_forms.each do |survey_form| %>
            <tr>
              <td data-title="Provinsi"><%= survey_form.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= survey_form.kabupaten %></td>
              <td data-title="Kecamatan"><%= survey_form.kecamatan %></td>
              <td data-title="Kelurahan"><%= survey_form.kelurahan %></td>
              <td data-title="Nama Lokasi"><%= survey_form.nama_lokasi %></td>
              <td data-title="Lattide"><%= survey_form.lattide %></td>
              <td data-title="Longitude"><%= survey_form.longitude %></td>
              <td data-title="Tanggal Dibuat"><%= survey_form.created_at.strftime '%d-%m-%Y' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>            
</div>          

app/views/wilayah_tengahs/kalimantan_barat.html.erb
 <div class="container-fluid">
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Tengah Provinsi Kalimantan Barat</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-1">
                <%= pie_chart SurveyForm.where(provinsi:"Kalimantan Barat").group(:kabupaten).count, discrete: true, donut:true, height: "400px", messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>
  </div>     

 
  <div class="container">
    <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Nama Lokasi</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
            <th style="text-align: center;">Tanggal Dibuat</th>
          </tr>
        </thead>

        <tbody>
          <% @survey_forms.each do |survey_form| %>
            <tr>
              <td data-title="Provinsi"><%= survey_form.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= survey_form.kabupaten %></td>
              <td data-title="Kecamatan"><%= survey_form.kecamatan %></td>
              <td data-title="Kelurahan"><%= survey_form.kelurahan %></td>
              <td data-title="Nama Lokasi"><%= survey_form.nama_lokasi %></td>
              <td data-title="Lattide"><%= survey_form.lattide %></td>
              <td data-title="Longitude"><%= survey_form.longitude %></td>
              <td data-title="Tanggal Dibuat"><%= survey_form.created_at.strftime '%Y-%m-%d' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>
</div>    
  </div>   

app/views/wilayah_tengahs/kalimantan_selatan.html.erb
 <div class="container-fluid">
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Tengah Provinsi Kalimantan Selatan</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-1">
                <%= pie_chart SurveyForm.where(provinsi:"Kalimantan Selatan").group(:kabupaten).count, discrete: true, donut:true, height: "400px", messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>
  </div>     

 
  <div class="container">
    <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Nama Lokasi</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
            <th style="text-align: center;">Tanggal Dibuat</th>
          </tr>
        </thead>

        <tbody>
          <% @survey_forms.each do |survey_form| %>
            <tr>
              <td data-title="Provinsi"><%= survey_form.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= survey_form.kabupaten %></td>
              <td data-title="Kecamatan"><%= survey_form.kecamatan %></td>
              <td data-title="Kelurahan"><%= survey_form.kelurahan %></td>
              <td data-title="Nama Lokasi"><%= survey_form.nama_lokasi %></td>
              <td data-title="Kelurahan"><%= survey_form.lattide %></td>
              <td data-title="Kelurahan"><%= survey_form.longitude %></td>
              <td data-title="Tanggal Dibuat"><%= survey_form.created_at.strftime '%Y-%m-%d' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>
</div>  
  </div>   

app/views/wilayah_tengahs/kalimantan_timur.html.erb
 <div class="container-fluid">
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Tengah Provinsi Kalimantan Timur</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-1">
                <%= pie_chart SurveyForm.where(provinsi:"Kalimantan Timur").group(:kabupaten).count, discrete: true, donut:true, height: "400px", messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>
  </div>     

  <div class="container">
    <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Nama Lokasi</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
            <th style="text-align: center;">Tanggal Dibuat</th>
          </tr>
        </thead>

        <tbody>
          <% @survey_forms.each do |survey_form| %>
            <tr>
              <td data-title="Provinsi"><%= survey_form.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= survey_form.kabupaten %></td>
              <td data-title="Kecamatan"><%= survey_form.kecamatan %></td>
              <td data-title="Kelurahan"><%= survey_form.kelurahan %></td>
              <td data-title="Nama Lokasi"><%= survey_form.nama_lokasi %></td>
              <td data-title="Kelurahan"><%= survey_form.lattide %></td>
              <td data-title="Kelurahan"><%= survey_form.longitude %></td>
              <td data-title="Tanggal Dibuat"><%= survey_form.created_at.strftime '%Y-%m-%d' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>
</div>  
  </div>   

app/views/wilayah_tengahs/kalimantan_utara.html.erb
 <div class="container-fluid">
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Tengah Provinsi Kalimantan Utara</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-1">
                <%= pie_chart SurveyForm.where(provinsi:"Kalimantan Utara").group(:kabupaten).count, discrete: true, donut:true, height: "400px", messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>
  </div>     

 
  <div class="container">
    <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Nama Lokasi</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
            <th style="text-align: center;">Tanggal Dibuat</th>
          </tr>
        </thead>

        <tbody>
          <% @survey_forms.each do |survey_form| %>
            <tr>
              <td data-title="Provinsi"><%= survey_form.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= survey_form.kabupaten %></td>
              <td data-title="Kecamatan"><%= survey_form.kecamatan %></td>
              <td data-title="Kelurahan"><%= survey_form.kelurahan %></td>
              <td data-title="Nama Lokasi"><%= survey_form.nama_lokasi %></td>
              <td data-title="Kelurahan"><%= survey_form.lattide %></td>
              <td data-title="Kelurahan"><%= survey_form.longitude %></td>
              <td data-title="Tanggal Dibuat"><%= survey_form.created_at.strftime '%Y-%m-%d' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>
</div>  
  </div>   

app/views/wilayah_tengahs/nusa_tenggara_barat.html.erb
 <div class="container-fluid">
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Tengah Provinsi Nusa Tenggara Barat</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-1">
                <%= pie_chart SurveyForm.where(provinsi:"Nusa Tenggara Barat").group(:kabupaten).count, discrete: true, donut:true, height: "400px", messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>
  </div>     

 
  <div class="container">
    <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Nama Lokasi</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
            <th style="text-align: center;">Tanggal Dibuat</th>
          </tr>
        </thead>

        <tbody>
          <% @survey_forms.each do |survey_form| %>
            <tr>
              <td data-title="Provinsi"><%= survey_form.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= survey_form.kabupaten %></td>
              <td data-title="Kecamatan"><%= survey_form.kecamatan %></td>
              <td data-title="Kelurahan"><%= survey_form.kelurahan %></td>
              <td data-title="Nama Lokasi"><%= survey_form.nama_lokasi %></td>s
              <td data-title="Kelurahan"><%= survey_form.lattide %></td>
              <td data-title="Kelurahan"><%= survey_form.longitude %></td>
              <td data-title="Tanggal Dibuat"><%= survey_form.created_at.strftime '%Y-%m-%d' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>
</div>  
  </div>   

app/views/wilayah_tengahs/nusa_tenggara_timur.html.erb
 <div class="container-fluid">
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Tengah Provinsi Nusa Tenggara Timur</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-1">
                <%= pie_chart SurveyForm.where(provinsi:"Nusa Tenggara Timur").group(:kabupaten).count, discrete: true, donut:true, height: "400px",messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>
  </div>     

 
  <div class="container">
    <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Nama Lokasi</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
            <th style="text-align: center;">Tanggal Dibuat</th>
          </tr>
        </thead>

        <tbody>
          <% @survey_forms.each do |survey_form| %>
            <tr>
              <td data-title="Provinsi"><%= survey_form.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= survey_form.kabupaten %></td>
              <td data-title="Kecamatan"><%= survey_form.kecamatan %></td>
              <td data-title="Kelurahan"><%= survey_form.kelurahan %></td>
              <td data-title="Nama Lokasi"><%= survey_form.nama_lokasi %></td>
              <td data-title="Kelurahan"><%= survey_form.lattide %></td>
              <td data-title="Kelurahan"><%= survey_form.longitude %></td>
              <td data-title="Tanggal Dibuat"><%= survey_form.created_at.strftime '%Y-%m-%d' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>
</div>  
  </div>   