config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'users'
  resources :form_barats 
  
  root :to => "pages#index"

  get 'wilayah_tengah' => 'wilayah_tengahs#index'
  get 'wilayah_tengah/gorontalo' => 'wilayah_tengahs#gorontalo'
  get 'wilayah_tengah/kalimantanbarat' => 'wilayah_tengahs#kalimantan_barat'
  get 'wilayah_tengah/kalimantanselatan' => 'wilayah_tengahs#kalimantan_selatan'
  get 'wilayah_tengah/kalimantantimur' => 'wilayah_tengahs#kalimantan_timur'
  get 'wilayah_tengah/kalimantanutara' => 'wilayah_tengahs#kalimantan_utara'
  get 'wilayah_tengah/nusatenggaratimur' => 'wilayah_tengahs#nusa_tenggara_timur'
  get 'wilayah_tengah/nusatenggarabarat' => 'wilayah_tengahs#nusa_tenggara_barat'
  get 'wilayah_tengah/sulawesitengah' => 'wilayah_tengahs#sulawesi_tengah'
  get 'wilayah_tengah/sulawesitenggara' => 'wilayah_tengahs#sulawesi_tenggara'

  get 'wilayah_tengah/mydata' => 'survey_forms#tengah_mydata'


  resources :survey_forms

  resources :users do
    resources :survey_forms
  end
end

app/controllers/survey_forms_controller.rb
class SurveyFormsController < ApplicationController
  before_action :set_survey_form, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :job_owner_tengah, only: [:edit, :update, :destroy]
  
  # GET /survey_forms
  # GET /survey_forms.json
  def index
    @survey_forms = SurveyForm.all
    if params[:search]
      @survey_forms = SurveyForm.search(params[:search]).order("created_at DESC").page(params[:page]).per_page(20)
    else
      @survey_forms = SurveyForm.all.order('created_at DESC').page(params[:page]).per_page(20)
    end

    respond_to do |format|
      format.html
      format.csv { send_data @survey_forms.to_csv }
      format.xls { send_data @survey_forms.to_csv(col_sep: "\t") }
    end
  end

  # GET /survey_forms/1
  # GET /survey_forms/1.json
  def show
  end

  # GET /survey_forms/new
  def new
    @survey_form = SurveyForm.new
  end

  # GET /survey_forms/1/edit
  def edit
    @user = current_user
    survey_forms = current_user.survey_forms
    @users = @user.survey_forms
  end

  def job_owner_tengah
     unless @survey_form.user_id == current_user.id
      flash[:notice] = 'Access denied as you are not owner of this Job'
      redirect_to wilayah_tengah_mydata_path
     end
    end

   def tengah_mydata
    @user = current_user
    survey_forms = current_user.survey_forms
    @users = @user.survey_forms
    #@form_barats = FormBarat.all
  end

  # POST /survey_forms
  # POST /survey_forms.json
  def create
    @survey_form = SurveyForm.new(survey_form_params)
    @survey_form = current_user.survey_forms.create(survey_form_params)
    
    respond_to do |format|
      if @survey_form.save
        format.html { redirect_to survey_forms_path, notice: 'Survey form was successfully created.' }
        format.json { render :show, status: :created, location: @survey_form }
      else
        format.html { render :new }
        format.json { render json: @survey_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_forms/1
  # PATCH/PUT /survey_forms/1.json
  def update
    respond_to do |format|
      if @survey_form.update(survey_form_params)
        format.html { redirect_to survey_forms_path, success: 'Survey form was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_form }
      else
        format.html { render :edit }
        format.json { render json: @survey_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_forms/1
  # DELETE /survey_forms/1.json
  def destroy
    @survey_form.destroy
    respond_to do |format|
      format.html { redirect_to survey_forms_url, notice: 'Survey form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_form
      @survey_form = SurveyForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_form_params
      params.require(:survey_form).permit(:side_id, :nama_site_id, :alamat, :kelurahan, :kecamatan, :kabupaten, :provinsi, :nama_lokasi, :lattide, :longitude, :jam_operasional, :id_pelanggan_listrik, :kapasitas, :lainnya_internet, :bandwidt_tersedia, :nama_operator_seluler, :kualitas_layanan, :jumlah_komputer, :perangkat_pendukung_lainnya, :nama_penanggung_jawab_lokasi_1, :kontak_penanggung_jawab_lokasi_1, :nama_penanggung_jawab_lokasi_2, :kontak_penanggung_jawab_lokasi_2, :keterangan_menuju_lokasi, :catatan_tambahan, :gambaran_menuju_lokasi, :surveyor, :project, :perangkat_lainnya,:kualitas_akses_internet, :photo_sketsa, :image_gedung, :image_rencana_tempat_perangkat, :image_genset, :image_lingkungan_depan, :image_lingkungan_belakang, :image_lingkungan_kiri, :image_lingkungan_kanan, :image_akses_ke_site, :image_akses_ke_site_1, :image_geotagging, :image_surveyor, :image_tambahan_photo_1, jenis_koneksi_1:[],  sumber_listrik:[], jenis_koneksi:[], transportasi_menuju_lokasi:[])
    end
end

app/helpers/survey_forms_helper.rb
module SurveyFormsHelper

	def checked(area)
		@survey_form.sumber_listrik.nil? ? false : @survey_form.sumber_listrik.match(area)
	end

	def checked1(area)
		@survey_form.jenis_koneksi.nil? ? false : @survey_form.jenis_koneksi.match(area)
	end

	def checked2(area)
		@survey_form.jenis_koneksi_1.nil? ? false : @survey_form.jenis_koneksi_1.match(area)
	end

	def checked3(area)
		@survey_form.transportasi_menuju_lokasi.nil? ? false : @survey_form.transportasi_menuju_lokasi.match(area)
	end
end

app/views/survey_forms/edit.html.erb
<center><h1>Editing Survey Form</h1></center>

<%= render 'form' %>

app/views/survey_forms/index.html.erb
  <style>
    body {
      background-color: #ccffff;
    }
    @media print {
    .no_print { 
        display: none; 
    }
}
  </style>

<p id="notice"><%= notice %></p>

<center><h1>Data Survey Wilayah Tengah</h1></center>
<br />
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag survey_forms_path, class: "no_print", :method => 'get' do %>
      <select class="selectpicker form-control" data-show-subtext="true" data-live-search="true" name="search" id="search">
              <option disabled selected>Pilih Provinsi</option>
              <option>Gorontalo</option>
              <option>Kalimantan Barat</option>
              <option>Kalimantan Selatan</option>
              <option>Kalimantan Timur</option>
              <option>Kalimantan Utara</option>
              <option>Nusa Tenggara Timur</option>
              <option>Nusa Tenggara Barat</option>
              <option>Sulawesi Tengah</option>
              <option>Sulawesi Tenggara</option>
      </select>
      <br /><br />
      <center><%= submit_tag "Search", class: "btn btn-success"%></center>
    <% end %>
  </div>
  <br /><br />
 
<div class="container-fluid">
<div class="col-md-12">
  <% if current_user %>
  <p class="no_print">
    Download Data:<br />
    <button class="btn btn-sm btn-danger" onclick="myFunction()">Print PDF</button>
  </p>
  <% end %>
  <div class="table-responsive">
    <table class="table" width="100%">
        <% @survey_forms.each do |survey_form| %>
          <tr>
            <th width="50%">Site ID</th>
            <td width="50%"><%= survey_form.side_id %></td>
          </tr>
          <tr>
            <th>Nama Site</th>
            <td><%= survey_form.nama_site_id %></td>
          </tr>
          <tr>
            <th>Provinsi</th>
            <td><%= survey_form.provinsi %></td>
          </tr>
          <tr>
            <th>Kabupaten</th>
            <td><%= survey_form.kabupaten %></td>
          </tr>
          <tr>
            <th>Kecamatan</th>
            <td><%= survey_form.kecamatan %></td>
          </tr>
          <tr>
            <th >Kelurahan</th>
            <td><%= survey_form.kelurahan %></td>
          </tr>
          <tr>
            <th >Alamat</th>
            <td><%= survey_form.alamat %></td>
          </tr>
          
          <tr>
            <th>Nama Lokasi</th>
            <td><%= survey_form.nama_lokasi %></td>
          </tr>
          <tr>
            <th>Surveyor</th>
            <td><%= survey_form.surveyor %></td>
          </tr>
          <tr>
            <th>Project</th>
            <td><%= survey_form.project %></td>
          </tr>
          <tr>
            <th>Lattide</th>
            <td><%= survey_form.lattide %></td>
          </tr>
          <tr>
            <th>Longitude</th>
            <td><%= survey_form.longitude %></td>
          </tr>
          <tr>
            <th>Sumber listrik</th>
            <td><%= survey_form.sumber_listrik %></td>
          </tr>
          <tr>
            <th>Jam operasional</th>
            <td><%= survey_form.jam_operasional %></td>
          </tr>
          <tr>
            <th>Id pelanggan listrik</th>
            <td><%= survey_form.id_pelanggan_listrik %></td>
          </tr>
          <tr>
            <th>Kapasitas</th>
            <td><%= survey_form.kapasitas %></td>
          </tr>
          <tr>
            <th>Jenis Koneksi Internet Eksisting</th>
            <td><%= survey_form.jenis_koneksi %></td>
          </tr>
          <tr>
            <th>Koneksi Internet Lainnya</th>
            <td><%= survey_form.lainnya_internet %></td>
          </tr>
          <tr>
            <th>Kualitas akses internet</th>
            <td><%= survey_form.kualitas_akses_internet %></td>
          </tr>
          <tr>
            <th>Bandwidt tersedia</th>
            <td><%= survey_form.bandwidt_tersedia %></td>
          </tr>
          <tr>
            <th>Jenis Koneksi Seluler</th>
            <td><%= survey_form.jenis_koneksi_1 %></td>
          </tr>
          <tr>
            <th>Nama operator seluler</th>
            <td><%= survey_form.nama_operator_seluler %></td>
          </tr>
          <tr>
            <th>Kualitas layanan</th>
            <td><%= survey_form.kualitas_layanan %></td>
          </tr>
          <tr>
            <th>Jumlah komputer</th>
            <td><%= survey_form.jumlah_komputer %></td>
          </tr>
          <tr>
            <th>Perangkat pendukung</th>
            <td><%= survey_form.perangkat_pendukung_lainnya %></td>
          </tr>
          <tr>
            <th>Lainnya</th>
            <td><%= survey_form.perangkat_lainnya %></td>
          </tr>
          <tr>
            <th>Nama penanggung jawab lokasi 1</th>
            <td><%= survey_form.nama_penanggung_jawab_lokasi_1 %></td>
          </tr>
          <tr>
            <th>Kontak penanggung jawab lokasi 1</th>
            <td><%= survey_form.kontak_penanggung_jawab_lokasi_1 %></td>
          </tr>
          <tr>
            <th>Nama penanggung jawab lokasi 2</th>
            <td><%= survey_form.nama_penanggung_jawab_lokasi_2 %></td>
          </tr>
          <tr>
            <th>Kontak penanggung jawab lokasi 2</th>
            <td><%= survey_form.kontak_penanggung_jawab_lokasi_2 %></td>
          </tr>
          <tr>
            <th>Transportasi menuju lokasi</th>
            <td><%= survey_form.transportasi_menuju_lokasi %></td>
          </tr>
          <tr>
            <th>Keterangan Menuju Lokasi</th>
            <td><%= survey_form.keterangan_menuju_lokasi %></td>
          </tr>
          <tr>
            <th>Gambaran menuju lokasi</th>
            <td><%= survey_form.gambaran_menuju_lokasi %></td>
          </tr>
          <tr>
            <th>Catatan Tambahan</th>
            <td><%= survey_form.catatan_tambahan %></td>
          </tr>
          <tr class="no_print">
            <th>Photo</th>
            <td><%= link_to 'Data Photo', survey_form, class: "btn btn-sm btn-success" %></td>
          </tr> 
          <tr>
            <th colspan="2"></th>
          </tr>     
        <% end %>
    </table>
  </div>
</div>
</div>

<script>
function myFunction() {
    window.print();
}
</script>

<script type="text/javascript">
$('select').select2({width: "100%"});
</script>

app/views/survey_forms/new.html.erb
<%= render 'layouts/navbar' %>
  <div class="container">
  <%= render 'form' %>
</div>

app/views/survey_forms/show.html.erb
 
 <style>
  body {
      background-color: #ccffff;
  }

  img {
    cursor: zoom-in;
  }
  @media print {
    .no_print { 
        display: none; 
  }
  </style>

<p id="notice"><%= notice %></p>

<center><h1>Data Image</h1></center>

<div class="container-fluid">
  <div class="col-md-12">
  <% if current_user %>
  <p class="no_print"> Download Data:<br />
    <button class="btn btn-sm btn-danger" onclick="myFunction()">Print PDF</button>
  </p>
  <% end %>
  <br />
    <div class="table-responsive">
      <table class="table" width="100%">
        <tr>
            <th width="50%">Site ID</th>
            <td width="50%"><%= @survey_form.side_id %></td>
          </tr>
          <tr>
            <th>Nama Site</th>
            <td><%= @survey_form.nama_site_id %></td>
          </tr>
        <tr>
          <th >Provinsi:</th>
          <td  width="50%"><%= @survey_form.provinsi %></td>
        </tr>
        <tr>
          <th  width="50%">Kecamatan:</th>
          <td  width="50%"><%= @survey_form.kecamatan %></td>
        </tr>
        <tr>
          <th  width="50%">Kelurahan:</th>
          <td  width="50%"><%= @survey_form.kelurahan %></td>
        </tr>
        <tr>
          <th>Nama Lokasi</th>
          <td><%= @survey_form.nama_lokasi %></td>
        </tr>
        <tr>
          <th>Photo Sketsa/Layout</th>
          <td><a href="#"><%= image_tag @survey_form.photo_sketsa.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Gedung</th>
          <td><a href="#"><%= image_tag @survey_form.image_gedung.url, style: "width:35%;",class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Rencana Tempat Perangkat</th>
          <td><a href="#"><%= image_tag @survey_form.image_rencana_tempat_perangkat.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Lingkungan Depan</th>
          <td><a href="#"><%= image_tag @survey_form.image_lingkungan_depan.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Lingkungan Belakang</th>
          <td><a href="#"><%= image_tag @survey_form.image_lingkungan_belakang.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Lingkungan Kiri</th>
          <td><a href="#"><%= image_tag @survey_form.image_lingkungan_kiri.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Lingkungan Kanan</th>
          <td><a href="#"><%= image_tag @survey_form.image_lingkungan_kanan.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Akses ke Site 1</th>
          <td><a href="#"><%= image_tag @survey_form.image_akses_ke_site.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Akses ke Site 2</th>
          <td><a href="#"><%= image_tag @survey_form.image_akses_ke_site_1.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>

        <tr>
          <th>Photo Geotagging</th>
          <td><a href="#"><%= image_tag @survey_form.image_geotagging.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Surveyor</th>
          <td><a href="#"><%= image_tag @survey_form.image_surveyor.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Tambahan 1</th>
          <td><a href="#"><%= image_tag @survey_form.image_tambahan_photo_1.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>

         <div class="modal fade" id="enlargeImageModal" tabindex="-1" role="dialog" aria-labelledby="enlargeImageModal" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                </div>
                <div class="modal-body">
                  <img src="" class="enlargeImageModalSource" style="width: 100%">
                </div>
              </div>
            </div>
          </div>

      </table>
    </div>
  </div>
</div>
<br>
<script>
  $(function() {
        $('img').on('click', function() {
        $('.enlargeImageModalSource').attr('src', $(this).attr('src'));
        $('#enlargeImageModal').modal('show');
      });
  });
</script>
<script>
function myFunction() {
    window.print();
}
</script>

app/views/survey_forms/tengah_mydata.html.erb
<div class="container">
<div class="table-responsive">
<table class="table table-stripted table-hover table-responsive">
  <thead>
    <tr>
            <th>Provinsi</th>
            <th>Kota / Kabupaten</th>
            <th>Kecamatan</th>
            <th>Kelurahan</th>
            <th>Action</th>
      
    </tr>
  </thead>  
  <tbody>     
       <% @users.each do |user| %>
            <tr>
              <td data-title="Provinsi"><%= user.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= user.kabupaten %></td>
              <td data-title="Kecamatan"><%= user.kecamatan %></td>
              <td data-title="Kelurahan"><%= user.kelurahan %></td>
              <td><%= link_to 'Show', user %>
              <%= link_to 'Edit', edit_survey_form_path(user) %>
              <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>  
            </tr>
    <% end %>
      </tbody>
</table>
</div>
</div>